### ISSUE TITLE
Support for Github Codespaces in addition to Binder

### ISSUE THREAD

**Issue by saulshanabrook** [executablebooks/thebe#522]
### Description / Summary

I am curious if this project would be open to adding support for starting machines with GitHub Codespaces, in addition to the default of Binder. We are using Codespaces as an easy way to spin up a demo machine for our private codebase. We are looking at building our documentation with Jupyter Book, which will be private until we open source things.

For this use case, I was curious if it might be possible to have a Jupyter Book privately hosted on Read the Docs use CodeSpaces to execute code inline in the docs. 

### Value / benefit

This would help us build interactive documentation while still allowing our code to remain private for the time being. Also, even if our code was open source, codespaces provides some benefits over Binder, in terms of keeping a machine open so that it could potentially be quicker to run code with an existing codespace over launching a new binder. Of course, the tradeoff is that it costs $$$ instead of being free for the users, and is not open source.

### Implementation details

* Github provides access to codespaces through their GraphQL API: https://docs.github.com/en/rest/reference/codespaces
* They use this in their CLI to list open ports and connect to SSH of a codespaces
* In a similar manner, if your codespaces starts a Jupyter on startup and exposes the port, then Binder could connect to that Jupyter server to create a kernel.

### Tasks to complete

- [ ] Decide if supporting codespaces would be in scope for this project
- [ ] Determine from a UX perspective how this would work. I assume it would require some Github authentication, and then also possibly the ability for the user to choose a codespaces to use? Or just try to find an existing one or create one?
- [ ] Look at CodeSpaces APIs to see how to get the port for Jupyter
- [ ] Create a test/demo project that starts Jupyter in codespaces and connects it to Thebe

**Comment by stevejpurves** [comment]
This is an interesting question @saulshanabrook !

Everything I've read so far about codespaces point at them being accessed via VSCode but what you are suggesting if I undestand is that a jupyter server would be running on an exposed port from the codespace docker container? Is it possible for that port to be exposes publically? or is that where the github auth comes in, i.e. you have to access that machine via github's API in some way?

**Comment by saulshanabrook** [comment]
@stevejpurves Yeah you can start services in codespaces and expose their ports. I am using this in a project to start JupyterLab when the codespaces launches and expose that port. In this way, it can function much like binder, just with a different default interface and is persistent.


> Is it possible for that port to be exposes publically?

Yes it is, you can expose it publicly for anyone without auth and also expose it for yourself, which is what I am doing.


In order to make a demo of this one would have to make a new org with codespaces enabled (which requires their basic plan of $4/month/user), start a jupyter server in a codespaces, and share the port or access it via the API.

Unfortunately, codespaces is not available on personal repos or free workspaces.

**Comment by stevejpurves** [comment]
@saulshanabrook I have a feeling including implementation here to specifically support codespaces, may be out of scope for thebe -- am I right in thinking that thebe can already be used to access Jupyter services running on code spaces as-is? once the auth and handshaking with the codespaces API was complete, thebe would be configured to connect to the Jupyter server as any other?

If that is the case then perhaps a separate library that uses thebe and takes case of the codespaces concerns is the best way forward.

[sphinx-thebe](https://github.com/executablebooks/sphinx-thebe) is already an example of this that uses thebe with sphinx and provides custom UI for juptyerbook. Maybe a `codespaces-thebe` to provide the necessary hookup/lookup is a better approach, and if non codespace specific upstream changes are needed here then we can make them.

**Comment by saulshanabrook** [comment]
> am I right in thinking that thebe can already be used to access Jupyter services running on code spaces as-is?

Ah I see, that makes sense to me. I didn't realize it was possible to use Thebe with an arbitrary existing exposed Jupyter server.

**Comment by stevejpurves** [comment]
@saulshanabrook that being said, if changes are needed here to help support that connection we can make them for sure.

**Comment by saulshanabrook** [comment]
Sounds good, closing this for now then.
